### ISSUE TITLE
Request: Access to pre-trained model checkpoints

### ISSUE THREAD

**Issue by PatrickTUM** [Orion-AI-Lab/KuroSiwo#1]
Yassou @ngbountos & colleagues,

congratulations and thanks for your nice work! This is to ask whether the benchmarked models' checkpoints are available anywhere or whether you are planning to share them. Specifically, it would be convenient to have access to the checkpoints of FlodViT and SNUNet, as these two perform very well and cover both segmentation plus change detection. 

I understand that the aim of the publication is in providing a benchmark rather than new SOTAs and that the training scripts are kindly provided by you ... BUT it would be awesomely convenient to having access to these checkpoints for some rapid prototyping and quick inference-only purposes : )

Cheers
Patrick

**Comment by ngbountos** [comment]
Hey @PatrickTUM,

I updated the README with the links for the weights of the top two models in our benchmark (FloodViT and SNUNet). The code  for the change detection models and training will be released in the coming week. I hope this helps you.
If you need more information feel free to contact us anytime :) 

Nikos.
