### ISSUE TITLE
Download only labeled images?

### ISSUE THREAD

**Issue by Frankie91** [Orion-AI-Lab/KuroSiwo#2]
Dear @ngbountos and colleagues,

First of all, congratulations and thank you for the impressive work. I have the following question: how should I proceed if I wanted to download only the labeled images relative to the flood events that took place in Europe?

Thank you in advance and best regards,
Daniele Francario

**Comment by ngbountos** [comment]
Hi @Frankie91,
you can download the data from this [link](https://www.dropbox.com/scl/fo/nkqaa9se5zl3yng4bdai4/h?rlkey=bro222cvgu4lo3b4towo6gbmm&dl=0). We split the dataset in 8 parts to make it easier to download. We did not group the events by continents, so you have to download everything and separate the events that you need (in this case the ones in Europe). Each event is associated with an id e.g `470`. In [catalogue.yaml](https://github.com/Orion-AI-Lab/KuroSiwo/blob/main/catalogue/catalogue.yaml) we provide all necessary information regarding the location of each event so you can identify which id's you need e.g:
```
 - act_id: 470
    act_region: Togo
    aois:
        aoi_name: Oti River
        cl_zone: 1
   ```
I hope this helps.

**Comment by Frankie91** [comment]
Good Morning @ngbountos,

Thanks for the quick answer, which does clarify how to find the events I'm looking for. To obtain a complete labeled image for the flood event that took place in Togo I should therefore select all the last tiles in every triplet with the act_id equal to 470, and merge them together. Is that correct?

**Comment by ngbountos** [comment]
Each event has three SAR images. Two before the event and one after. Each sample is stored as triplets (pre event 1, pre event 2 and post event) of patches of 224x224 pixels in a subdirectory of the given activation id and aoi as specified in the `catalogue.yaml` e.g `/118/01/eef3611509285592aa0ffe3fe1856d53` . `01` signifies the aoi under study. In the `00` subfolder we store the patches coming from the area outside of the aois. If you want to recreate the initial image you have to take all patches of a certain timestep (let's say the post event) and merge them. The patches are georeferenced so it should be easy.

**Comment by Frankie91** [comment]
Perfect, thanks again for all the detailed clarifications!
