### ISSUE TITLE
ViT pretrained model does not run

### ISSUE THREAD

**Issue by Multihuntr** [Orion-AI-Lab/KuroSiwo#3]
Hello! Thanks for making an interesting dataset and providing pretrained weights. I'm trying to use the pretrained weights and I'm coming up against a problem. 

The ViT model doesn't seem to run. Here's a small example to observe the problem (run from the root of this git)

```python
import torch
model = torch.load('./best_segmentation.pt', map_location=torch.device('cpu'))
inp = torch.randn(4, 6, 224, 224)
out = model(inp)
```

It gives an einops error: 

```
einops.EinopsError:  Error while processing rearrange-reduction pattern "b (h w) c -> b (c) h w".
 Input tensor shape: torch.Size([4, 1024]). Additional info: {'h': 14, 'w': 14}.
 Wrong shape: expected 3 dims. Received 2-dim tensor.
```
The error points me to `models/model_utilities.py:86`. So far as I can see, this line is supposed to take the output of a `vit_pytorch.vit.ViT` model and put it through an `einops.rearrange(x, "b (h w) c -> b (c) h w")` to reshape it into an image-like structure. But the ViT [always outputs a tensor shaped `[B, C]`](https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/vit.py#L124), not `[B, N, C]`. So, I'm a bit confused. The shapes don't match! Am I using it wrong? What should it be doing?

P.S. I am writing a [`hubconf.py`](https://pytorch.org/docs/stable/hub.html) so that these pretrained models can be more easily used by others (and me). I will put in a pull request later, once I sort this out. I reckon I've figured out the SNUNet already.

**Comment by ngbountos** [comment]
Hey @Multihuntr ,
Thank you for your efforts and for raising this issue. Indeed, we are using a slightly modified version of the ViT found in vit_pytorch, which I forgot to include in the repo. In the initial implementation, the output of the ViT is either the mean of the tokens or the classification token. In our case we want to utilize the whole sequence for the segmentation part. I have updated the repo with the modified ViT and changed the url for the [FloodViT](https://www.dropbox.com/scl/fi/srw7u4cw1gtxrf4xzmsh7/floodvit.pt?rlkey=snskpq1qrdav5u2jya8k2bocg&dl=0) in the README. 

You can use the updated checkpoint as usual e.g:
```
import torch

checkpoint = torch.load('floodvit.pt', map_location='cpu')

print(checkpoint)

a = torch.randn(4,6,224,224)
out = checkpoint(a)
print(out.shape) # (4, 3, 224, 224)
```

Let me know if this solved your issue.

**Comment by Multihuntr** [comment]
Your logic to use the full sequence of tokens makes sense. It seems like an oversight of the ViT implementation that it does not let you output all of the tokens.

Unfortunately the new weights do not work. It now fails when trying to `torch.load`. It tells me that `No module named models.vision_transformer`. I assume that you have a `models/vision_transformer.py` file locally which has the correct ViT implementation? If so, you will need to commit that to the repo for these new linked weights to work.

I'm not sure if you know this - and I mean no offence by explaining if you do - but, `torch.save` pickles the object without storing the python code. In order to `torch.load`, the same code structures need to be available in the environment with precisely the same names. Otherwise, it can't unpickle. Which is what is happening here; you have a `models/vision_transformer.py` file, so it works for you, but no one else does, so it does not work for them.

**Comment by ngbountos** [comment]
Hey @Multihuntr ,

Did you try to pull the new updates? The vision_transformers.py is already in the models directory.

Nikos.

**Comment by Multihuntr** [comment]
🤦  My apologies. Thanks for that. It works now.
(I saw the URL update, but didn't notice it was in two different commits)
